compatibility_date = "2021-11-01"
compatibility_flags = []
name = "vavite-testbed"
route = ''
type = "javascript"
usage_model = ''
workers_dev = true
zone_id = ''

[build]
command = "DEPLOY_TARGET=cfw npm run build"

[build.upload]
dir = "./dist/cloudflare-workers-bundle"
format = "modules"
main = "./index.js"

[[build.upload.rules]]
globs = ["**/*.js"]
type = "ESModule"
